version: '3.2'
services:
  legacywebshop:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      local_dev_net:
          aliases:
              - legacywebshop

  microservice-kategorien:
    build:
      context: ./
      dockerfile: ./docker/DockerfileKategorien
    depends_on:
      web-shop-db-image:
        condition: service_healthy
    environment:
      MYSQL_HOST: web-shop-db-image
    ports:
      - "8081:8080"
    networks:
      local_dev_net:
        aliases:
          - kategorien

  microservice-products:
    build:
      context: ./
      dockerfile: ./docker/DockerfileProducts
    depends_on:
      web-shop-db-image:
        condition: service_healthy
    environment:
      MYSQL_HOST: web-shop-db-image
    ports:
      - "8082:8080"
    networks:
      local_dev_net:
        aliases:
          - products

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    healthcheck:
      test: mysql -u root -pc8de110f37300a53a971749 -e exit
      retries: 10
      start_period: 60s
      start_interval: 20s
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

networks:
  local_dev_net:
    driver: bridge
