# Default values for hska-vis-categories.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: koph1033/hska-vis-legacy
  tag: monolith-0.1.0

microservices:
  products:
    host: products.products
  categories:
    host: categories.categories

ingress:
  name:
    enabled: false
    value: public