apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monolith-ingress
  labels:
    app: ingress-hska-vis
  annotations:
    {{- if .Values.ingress.name.enabled }}
    kubernetes.io/ingress.class: {{ .Values.ingress.name.value | quote }}
    {{- else }}
    kubernetes.io/ingress.class: "istio"  # Tell Kubernetes to use Istio as the ingress controller
    {{- end }}
spec:
  {{- if .Values.ingress.name.enabled }}
  ingressClassName: {{ .Values.ingress.name.value }}
  {{- end }}
  # tls:
  #   - hosts:
  #       - {{ .Values.Second }}.{{ .Values.Top }}
  #     secretName: <secret>
  # host: {{ .Values.Second }}.{{ .Values.Top }}
  rules:
    - http:
        paths:
          - path: /EShop-1.0.0
            pathType: Prefix
            backend:
              service:
                name: monolith
                port:
                  number: 8080