apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hska-vis-products
  name: products
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hska-vis-products
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hska-vis-products
    spec:
      containers:
        - image: {{ .Values.image.name }}{{ ":" }}{{ .Values.image.tag }}
          name: products
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: products-database-config
                  key: MYSQL_HOST
            - name: PRODUCTS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: products-database-config
                  key: PRODUCTS_DB_NAME
            - name: PRODUCTS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: products-database-config
                  key: PRODUCTS_DB_USER
            - name: PRODUCTS_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: products-credentials
                  key: MYSQL_PASSWORD
            - name: CATEGORIES_HOST
              valueFrom:
                configMapKeyRef:
                  name: products-microservice-config
                  key: CATEGORIES_HOST
          ports:
          - containerPort: 8080
          resources: {}
      restartPolicy: Always
