apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hska-vis-categories
  name: categories
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hska-vis-categories
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        service: hska-vis-categories
    spec:
      containers:
        - image: koph1033/hska-vis-legacy:categories-0.1.0
          name: categories
          env:
            - name: MYSQL_HOST
              value: mysql.mysql
          ports:
          - containerPort: 8080
          resources: {}
      restartPolicy: Always
