apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hska-vis-products
  name: products
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hska-vis-products
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        service: hska-vis-products
    spec:
      containers:
        - image: koph1033/hska-vis-legacy:products-0.1.0
          name: products
          env:
            - name: MYSQL_HOST
              value: mysql.mysql
            - name: CATEGORIES_HOST
              value: categories.categories
            - name: PRODUCTS_DB_USER
              value: productsuser
            - name: PRODUCTS_DB_PWD
              valueFrom:
                secretKeyRef:
                  name: products-credentials
                  key: MYSQL_PASSWORD
          ports:
          - containerPort: 8080
          resources: {}
      restartPolicy: Always
