apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ "c8de110f37300a53a971749" | b64enc }}
  MYSQL_PASSWORD: {{ "240b2c6d58ff2ce2f508b49f" | b64enc }}